<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eml</string>
		<string>msg</string>
		<string>mbx</string>
		<string>mboxz</string>
	</array>
	<key>name</key>
	<string>Email (TextMate syntax)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?ix)^((.*)?-Signature|Authentication-results|DomainKey-Signature|Received-SPF)(:)</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?ix)^x-([a-z0-9-]+)(:)</string>
			<key>name</key>
			<string>storage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)^([A-Z][a-zA-Z0-9-]+)(:)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?ix)((&lt;?) [-a-z0-9.:_]+@[-a-zA-Z0-9.]+ (&gt;?))</string>
			<key>name</key>
			<string>markup.underline.link</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x) ^ (?:[A-Za-z0-9+/]{4})+ (?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)=([0-9a-fA-F]{2})</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)=\?(utf-8|windows-1251)\?B\?(.*)\?=</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?ix)boundary=(.+)</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?ix)^--[a-zA-Z0-9-=_?:]+(--)?$</string>
			<key>name</key>
			<string>constant.character</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(?=&lt;)</string>
			<key>push</key>
			<string>Packages/HTML/HTML.sublime-syntax</string>
			<key>with_prototype</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=&gt;)\s*$</string>
					<key>pop</key>
					<true/>
				</dict>
				<dict>
					<key>match</key>
					<string>[.@"]</string>
					<key>pop</key>
					<false/>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;script&gt;</string>
			<key>push</key>
			<string>Packages/JavaScript/JavaScript.sublime-syntax</string>
			<key>with_prototype</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?=&lt;/script&gt;)</string>
					<key>pop</key>
					<true/>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.eml</string>
	<key>uuid</key>
	<string>f1af3e13-5554-4d31-be65-11ab69f42c01</string>
</dict>
</plist>
