<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eml</string>
		<string>email</string>
		<string>mail</string>
		<string>mime</string>
	</array>
	<key>name</key>
	<string>EML (E-Mail)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(\S|&lt;)"[a-zA-Z0-9. \+\_\-]+"\s*&amp;lt;[a-zA-Z0-9.\-]+\@[a-zA-Z0-9.\-]+&amp;gt;(\S|&gt;)</string>
			<key>name</key>
			<string>markup.underline.link.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\S|&lt;)[a-zZ-Z0-9.\+\_\-]*\s*&amp;lt;[a-zA-Z0-9.\-]+\@[a-zA-Z0-9.\-]+&amp;gt;(\S|&gt;)</string>
			<key>name</key>
			<string>markup.underline.link.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(|&lt;)[a-zA-Z0-9.\+\_\-]+\@[a-zA-Z0-9.\-]+(&gt;|)</string>
			<key>name</key>
			<string>markup.underline.link.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)accept-language.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)authentication-results.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)auto-submitted.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)bcc.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)cc.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)charset.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)comments.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-class.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-description.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-disposition.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-id.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-language.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-transfer-encoding.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)content-type.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)errors-to.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)date.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)delivered-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)delivery-date.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)dkim-signature.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)domainkey-signature.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)envelope-from.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)envelope-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)enverlope-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)from.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)importance.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)in-reply-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)keywors.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)list-help.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)list-id.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)list-post.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)list-unsubscribe.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)message-id.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)mime-version.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)msmail-priority.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)precedence.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)priority.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)received-spf.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)received.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)references.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)reply-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)return-path.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)sender.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)sent:.*?</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)subject.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)thread-index.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)thread-topic.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)to:.*?</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)user-agent.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-bcc.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-cc.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-date.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-from.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-message-id.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-reply-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-sender.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)resent-to.*?:</string>
			<key>name</key>
			<string>keyword.control.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-antiabuse.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-auto-response-suppress.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-bulkmail.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-campaign.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-campaignid.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-cmae-analysis.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-cmae-score.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-eopattributedmessage.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-exchange-antispam-report-cfa-test.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-failed-recipients.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-feedback-id.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-filtered.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-forefront-antispam-report.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-forefront-prvs.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-forwarded-for.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-forwarded-to.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-gm-message-state.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-gmail-received.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-google-dkim-signature.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-loop.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mailer.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mailguard-id.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mailguard-uid.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mailgun-sid.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mailing-list.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mandrill-user.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mc-unique.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mc-user.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mcda.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-microsoft-antispam.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mimecast-impersonation-protect.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mimeole.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mozilla-status.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-mozilla-status2.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-exchange-crosstenant-fromentityheader.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-exchange-crosstenant-id.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-exchange-crosstenant-originalarrivaltime.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-exchange-messagesentrepresentingtype.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-exchange-transport-crosstenantheadersstamped.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-exchange-transport-fromentityheader.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-has-attach.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-office365-filtering-correlation-id.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ms-tnef-correlator.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-original-authentication-results.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-original-to.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-originalarrivaltime.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-originating-email.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-originating-ip.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-originatororg.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-pstn-levels.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-pstn-neptune.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-received.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-report-abuse.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-sender.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-source-args.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-source-dir.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-source.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam-checker-version.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam-level.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam-status.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam-zendesk-report.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam-zendesk-score.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam_bar.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam_report.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam_report:.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam_score.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-spam_score_int.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-tmn.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-virus-scanned.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-yahoo-newman-id.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-yahoo-newman-property.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ymail-isg.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?i)x-ymail-osg.*?:</string>
			<key>name</key>
			<string>markup.italic.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)7bit</string>
			<key>name</key>
			<string>constant.language.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)base64</string>
			<key>name</key>
			<string>constant.language.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)multipart\/.*:</string>
			<key>name</key>
			<string>constant.language.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)image\/.*;</string>
			<key>name</key>
			<string>constant.language.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)text\/.*;</string>
			<key>name</key>
			<string>constant.language.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)boundary</string>
			<key>name</key>
			<string>constant.language.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^--(?!&gt;).*</string>
			<key>name</key>
			<string>support.constant.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[|&gt;].*</string>
			<key>name</key>
			<string>string.quoted.other.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$</string>
			<key>name</key>
			<string>comment.line.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=09</string>
			<key>name</key>
			<string>comment.line.eml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=20</string>
			<key>name</key>
			<string>comment.line.eml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.eml</string>
	<key>uuid</key>
	<string>f1af3e13-5554-4d31-be65-11ab69f42c01</string>
</dict>
</plist>
